### PR TITLE
Pylint solve

### PR DESCRIPTION
**Pull request by kooyunmo**
Add docstrings to Django files to resolve the pylint errors

### CODE REVIEW

**Comment by nevivurn** [comment]
Remember to add `pylint-django` to `requirements-dev.txt`

**Comment by kooyunmo** [comment]
Got it. I added it to the requirements list.

## Issue
I tried to exclude `migrations` folder from pylintrc like [this link](https://stackoverflow.com/questions/16559810/pylint-ignore-multiple-in-rcfile) explains, but it doesn't work.

```
# Add files or directories to the blacklist. They should be base names, not
# paths.
ignore=CVS,migrations   <--- I added migrations here...!!!
```

**Comment by nevivurn** [comment]
Pylint is already not going through the migrations (or at least doesn't report any warnings on them).

https://travis-ci.com/swsnu/swpp2019-team20/jobs/249692949#L225 it seems like the only linter errors left are on the `account/test.py` file.

On the other hand, we should probably avoid tracking coverage of migration files

https://travis-ci.com/swsnu/swpp2019-team20/jobs/249692949#L250

since those are auto-generated. Adding `--omit '*/migrations/*'` should work.

**Comment by kooyunmo** [comment]
OK, I fixed python script part of`.traivs.yml` like below. I gave `--omit` options to `*/migrations/*`, `manage.py`, `*/wsgi.py`.

```
script:
        - pylint --load-plugins pylint_django **/*.py
        - coverage run --branch --source='.' --omit='*/migrations/*','manage.py','*/wsgi.py' ./manage.py test
        - coverage report -m --fail-under=90
```

**Comment by kooyunmo** [comment]
At this point, the only reason why it cannot pass the test is 'test coverage'.
However, since I wrote the Django codes not to be interactable with frontend side, I need to make changes on almost every backend file before writing the test code to increase the coverage.  Do you think it is better to do it in this PR, or make another branch and work on there?

**Pull request merged**
